# Configuration file for PokerNowHH scripts, including stats.py

# Setting test_run to true uses an alternate 'test' set of input and output databases.
# Useful for testing and debugging, as it leaves the 'real' databases untouched. (default: false)
test_run = true

# Time difference in days before a hand is considered to be part of a new session (default: 0.2)
time_diff = 0.2

# Database names and settings:
# db_name: Name of the database
# db_name_test: Name of the test database used when test_run = true
# hh_subdir: Subdirectory where unread hand history files are kept
# ...use "" for no subdirectory, and "subdir\\" for Windows environments
# is_tourney: Boolean to indicate whether this database consists of tournament hands (default: false)
# ...For meaningful stats, a database should consist exclusively of either tournament hands or cash game hands
# clear_db: Flag to delete the tables in this database, other than PlayerNames/Aliases (default: false)
[[db_list]]
db_name = "hand_history.sqlite"
db_name_test = "hand_history_test.sqlite"
hh_subdir = ""
is_tourney = false
clear_db = false

# The scripts are capable of handling arbitrarily many databases for different poker groups (player names are shared
# between all databases in case players overlap between groups). To maintain another database, simply add another
# instance of [[db_list]] with the proper variables underneath. The first database will always be treated as
# the main database, so be sure that the most important database is listed first (above).
[[db_list]]
db_name = "hh_sudbury.sqlite"
db_name_test = "hh_sudbury_test.sqlite"
hh_subdir = "Sudbury\\"
is_tourney = true
clear_db = false

[[db_list]]
db_name = "hh_fft.sqlite"
db_name_test = "hh_fft_test.sqlite"
hh_subdir = "FFT\\"
is_tourney = true
clear_db = false

[[db_list]]
db_name = "hh_shakeweights.sqlite"
db_name_test = "hh_shakeweights_test.sqlite"
hh_subdir = "Shakeweights\\"
is_tourney = false
clear_db = false

# Name of the small output database and the number of days to retain.
# There may be some fuzziness around begin and end dates due to time zones and long sessions,
# so err on the larger side. (default: 32)
[small_db]
out_name = "hh_small.sqlite"
out_name_test = "hh_small_test.sqlite"
num_days = 32

##########
# DO NOT EDIT BELOW THIS LINE
# Shared constants across scripts

# actions for database
[const]
POST_VAL = 1
POST_MISSING_VAL = 2  # missing blind post, not credited to player
POST_MISSED_VAL = 3  # missed blind post, credited to player
FOLD_VAL = 4
CHECK_VAL = 5
CALL_VAL = 6
BET_VAL = 7
RAISE_VAL = 8

# tournament actions for database
QUIT_VAL = 0
BUYIN_VAL = 1
REBUY_VAL = 2

# streets for database
PREFLOP_VAL = 1
FLOP_VAL = 3  # flop=3 is more human readable
TURN_VAL = 4
RIVER_VAL = 5
SHOWDOWN_VAL = 6

# blind values to add to position; SB is biggest because it's the worst position
STRADDLE_VAL = 10
BB_VAL = 20
SB_VAL = 30

# minimum and maximum positions at table
POS_MIN = 1  # button
POS_MAX = 8  # utg at 10-player table
