# Configuration file for PokerNowHH scripts, including stats.py
# Non-standard settings for standalone stats.py demo without other project scripts

# Setting test_run to true uses an alternate 'test' database, and also clears it by default.
# Useful for testing and debugging, as it leaves the 'real' database untouched. (default: false)
# Note: For the demo, this is set to true, but both the 'real' and 'test' databases are the same sample database.
test_run = true

# Time difference in days before a hand is considered to be part of a new session (default: 0.2)
time_diff = 0.2

# Database names and settings:
# db_name: Name of the database
# db_name_test: Name of the test database used when test_run = true
# hh_subdir: Subdirectory where unread hand history files are kept
# ...use "" for no subdirectory, and "subdir\\" for Windows environments
# is_tourney: Boolean to indicate whether this database consists of tournament hands (default: false)
# ...For meaningful stats, a database should consist exclusively of either tournament hands or cash game hands
# clear_db: Boolean to prompt to delete the tables in this database, other than PlayerNames/Aliases (default: false)
# ...Note that test_run = true automatically clears the test database without prompting
[[db_list]]
db_name = "hh_demo.sqlite"
db_name_test = "hh_demo.sqlite"
hh_subdir = ""
is_tourney = false
clear_db = false

# The scripts are capable of handling arbitrarily many databases for different poker groups (player names are shared
# between all databases in case players overlap between groups). To maintain another database, simply add another
# instance of [[db_list]] with the proper variables underneath. The first database will always be treated as
# the main database, so be sure that the most important database is listed first (above).

# [[db_list]]
# db_name = "another.sqlite"
# db_name_test = "another_test.sqlite"
# hh_subdir = "Another\\"
# is_tourney = false
# clear_db = false

# Name and settings for the optional small output database. The small database retains only the most recent hands
# and removes players' last names to facilitate posting stats publicly via tools like Tableau.
# It is based on the main (first) database only. Not very meaningful for the demo.
# out_name: Name of the small output database
# out_name_test: Name of the small output test database when test_run = true
# num_days: The number of days to retain (default: 32)
# ...There may be some fuzziness around begin and end dates due to time zones and sessions that span midnight
# create_small: Boolean to create the optional small output database (default: true)
# ...For the demo, this is set to false, because the sample database is too old to produce any recent hands
[small_db]
out_name = "hh_small_test.sqlite"
out_name_test = "hh_small_test.sqlite"
num_days = 32
create_small = false

####################
# DO NOT EDIT BELOW THIS LINE
# Shared constants across scripts

# actions for database
[const]
POST_VAL = 1
POST_MISSING_VAL = 2  # missing blind post, not credited to player
POST_MISSED_VAL = 3  # missed blind post, credited to player
FOLD_VAL = 4
CHECK_VAL = 5
CALL_VAL = 6
BET_VAL = 7
RAISE_VAL = 8

# tournament actions for database
QUIT_VAL = 0
BUYIN_VAL = 1
REBUY_VAL = 2

# streets for database
PREFLOP_VAL = 1
FLOP_VAL = 3  # flop=3 is more human readable
TURN_VAL = 4
RIVER_VAL = 5
SHOWDOWN_VAL = 6

# blind values to add to position; SB is biggest because it's the worst position
STRADDLE_VAL = 10
BB_VAL = 20
SB_VAL = 30

# minimum and maximum positions at table
POS_MIN = 1  # button
POS_MAX = 8  # utg at 10-player table
